### ISSUE TITLE
add some mqtt payload demo

### ISSUE THREAD

**Issue by fireport** [hsakoh/switchbot-mqtt#33] opened 2024-08-02 10:06 UTC
I struggle to find the mqtt payload to set a disposable pin on my keypad Pro.
Using the test page is fine but having the corresponding generated payload should be nice.
Some automation examples should be nice too.

**Comment by fireport** [comment] 2024-08-02 14:31
Following your hints I tried to execute the code in this YAML but unfortunately without luck.
Can you help me ?

```

action:
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: "{ \t\"CommandType\": \"command\", \t\"Command\": \"createKey\", \t\"ParamName\": \"name\", \t\"ParamValue\": \"topolino\" }"
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: "{ \t\"CommandType\": \"command\", \t\"Command\": \"createKey\", \t\"ParamName\":  \"type\", \t\"ParamValue\": \"disposable\" }"
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: "{ \t\"CommandType\": \"command\", \t\"Command\": \"createKey\", \t\"ParamName\": \"password\", \t\"ParamValue\": \"123456\" }"
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: "{ \t\"CommandType\": \"command\", \t\"Command\": \"createKey\", \t\"ParamName\": \"startTime\", \t\"ParamValue\": \"1722770320\" }"
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: "{ \t\"CommandType\": \"command\", \t\"Command\": \"createKey\", \t\"ParamName\": \"endTime\", \t\"ParamValue\": \"1722773920\" }"

```

**Comment by hsakoh** [comment] 2024-08-02 14:45
The input is correctly done. I believe the "button pressed" message is missing.
(For curtains, it's 3 parameters + "button pressed" for a total of 4 messages.
For the keypad, it should be 5 parameters + "button pressed" for a total of 6 messages.)
![image](https://github.com/user-attachments/assets/86741ca3-8c96-444f-b9b3-40974dd597d6)

What happens if you send the following message at the end?

```
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: "{ \t\"CommandType\": \"command\", \t\"Command\": \"createKey\", \t\"ParamName\": \"btn\", \t\"ParamValue\": \"action\" }"
```

**Comment by fireport** [comment] 2024-08-02 15:01
nope
`  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: "{ \t\"CommandType\": \"command\", \t\"Command\": \"createKey\", \t\"ParamName\": \"btn\", \t\"ParamValue\": \"action\" }"
	  `

**Comment by hsakoh** [comment] 2024-08-02 15:10
* Have you checked the corresponding KeyPad checkbox in the Ingress page device configuration and saved it?
  * Can you provide a screenshot of the device configuration screen?
* After checking and saving, did you start (or restart) the MQTT core service?
* Is there any output in the add-on logs?
  * Can you provide the add-on logs from the start of the add-on (including service start) up until after the MQTT message has been sent?
* What is the reason for not using the MQTT integration? (I'd like to know this for future reference.)

**Comment by fireport** [comment] 2024-08-02 15:30
![immagine](https://github.com/user-attachments/assets/bc6dd98b-cdf2-4fc1-954d-8eda3853b834)


`
[logs.txt](https://github.com/user-attachments/files/16472364/logs.txt)
`

How I can use the MQTT Integration ? Maybe I don't understand your question ?

**Comment by hsakoh** [comment] 2024-08-02 15:43
The MQTT integration is a standard feature of Home Assistant that communicates with an MQTT broker to discover devices and send commands.

By specifying the broker in the MQTT integration settings screen, you can automatically detect and use devices and entities on Home Assistant through the MQTT Discovery mechanism.

You can find more information and configure it from the following URL:
[MQTT Integration](https://www.home-assistant.io/integrations/mqtt/#broker-configuration)

**Comment by hsakoh** [comment] 2024-08-02 15:51
I've reviewed the logs and it appears that the createKey command has been successfully executed 9 times at the following times:

L.33  15:42:00
L.40  16:08:54
L.48  16:09:54
L.51  16:16:39
L.54  16:17:54
L.59  16:24:41
L.86  16:49:35
L.88  16:52:28
L.100  17:25:05

Were all these operations performed from the Ingress page's command test screen? (The log does not differentiate between MQTT messages and the test screen operations.)

**Comment by fireport** [comment] 2024-08-04 13:40
this is the screenshot related to a key creation that is successful
![immagine](https://github.com/user-attachments/assets/2cb7ebe8-33c5-4459-a464-387ee5bb6a83)
If using the mqtt integration, after deleting the key, the operation is unsuccessful
![immagine](https://github.com/user-attachments/assets/a3e713a2-7691-48f3-acc7-029da05437ba)

**Comment by hsakoh** [comment] 2024-08-04 14:02
From the second screenshot, it appears that control via MQTT integration is being displayed.

You mentioned that "after deleting the key, the operation is unsuccessful." What specifically leads you to conclude that it is unsuccessful? 
My understanding is that MQTT integration button operations do not provide direct feedback in the Home Assistant UI, so there shouldn't be any direct indication of unsuccessful.

Could you provide the logs before and after pressing the "createKey" button (labeled "PREMI" in the screenshot)?

I would expect to see logs similar to the following:
```
17:25:01 trce: SwitchBotMqttApp.Logics.SwitchBotApiClient[0] Send POST,devices/xxxxxxxxxxxxx/commands
17:25:05 trce: SwitchBotMqttApp.Logics.SwitchBotApiClient[0] Response POST,https://api.switch-bot.com/v1.1/devices/xxxxxxxxxxxxx/commands,{"statusCode":100,"body":{"commandId":"CMD111111111111"},"message":"success"}
```

If there are no API logs being output, could you check what message was published to the MQTT topic switchbot/{deviceId}/cmd from the MQTT integration?

**Comment by fireport** [comment] 2024-08-04 14:33
Dear @hsakoh,

I solved it using this code. There were a lot of escape characters that I think may have confused the API parser.
If you think it may be helpful, you could add this as an example in your documentation.

Thanks a lot!
`action:
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      payload: >-
        { "CommandType": "command", "Command": "createKey", "ParamName": "name",
        "ParamValue": "topolino" }
      topic: switchbot/XXXXXXXXXXXX/cmd
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: >-
        { "CommandType": "command", "Command": "createKey", "ParamName": 
        "type", "ParamValue": "a one-time passcode." }
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: >-
        { "CommandType": "command", "Command": "createKey", "ParamName":
        "password", "ParamValue":"123456789" }
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: >-
        { "CommandType": "command", "Command": "createKey", "ParamName":
        "startTime", "ParamValue": "1722848965" }
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: >-
        { "CommandType": "command", "Command": "createKey", "ParamName":
        "endTime", "ParamValue": "1722867782"}" }
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: >-
        { "CommandType": "command", "Command": "createKey", "ParamName": "btn",
        "ParamValue": "action" }`

**Comment by hsakoh** [comment] 2024-08-04 14:51
I'm glad the issue has been resolved.

I understand that you confirmed the operation by publishing the MQTT message directly. Regarding the parameter name `type`, the parameter value `disposable` was incorrect, and the correct value was `a one-time passcode` as shown in the dropdown list.

This means the value must match exactly with the text in the dropdown list in MQTT integration, which differs from the API input values. If a value not listed in the dropdown is sent in the MQTT message, the command is sent with an empty value.

Have you confirmed the operation from MQTT integration? If the operation seems unreliable, explicitly reselecting the dropdown options might help synchronize the state, especially after restarting the add-on, which can cause the add-on's internal state to be lost.

**Comment by hsakoh** [comment] 2024-08-04 14:56
Regarding the message③, since it is designed to be sent by the MQTT integration, I cannot guarantee that its payload format and other details will be maintained in the future. It is not intended for external direct payload transmission. Therefore, I am not considering documenting it at this time.

Since you have summarized it well enough for those who may encounter this issue, I think that will suffice for now.

If there are no additional questions, I would like to close this issue.

**Comment by fireport** [comment] 2024-08-04 16:29
Yes, for sure! You should close the ticket.

**Closed** 2024-08-09 19:37 UTC
